REPLAY_MEMORY_SIZE: 50_000
MIN_REPLAY_MEMORY_SIZE: 1_000
MODEL_NAME: '16th'
MINIBACH_SIZE: 64
DISCOUNT: 0.99
UPDATE_TARGET_EVERY: 5
MIN_REWARD: -90
EPISODES: 80000

epsilon: 1
EPSILON_DECAY: 0.9999342140184785
MIN_EPSILON: 0.001
AGGREGATE_STATS_EVERY: 50
SAVE_EVERY: 1000
EPISODE_LENGTH: 7